**Principal Component Analysis (PCA) on Taxi Dataset**

In [41]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import metrics

In [42]:
# Load the Taxi dataset
taxis_df = sns.load_dataset("taxis")
taxis_df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [43]:
# Data Preprocessing
taxis_df.describe()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total
count,6433,6433,6433.000000,6433.000000,6433.000000,6433.00000,6433.000000,6433.000000
mean,2019-03-16 08:31:28.514223616,2019-03-16 08:45:49.491217408,1.539251,3.024617,13.091073,1.97922,0.325273,18.517794
min,2019-02-28 23:29:03,2019-02-28 23:32:35,0.000000,0.000000,1.000000,0.00000,0.000000,1.300000
25%,2019-03-08 15:50:34,2019-03-08 16:12:51,1.000000,0.980000,6.500000,0.00000,0.000000,10.800000
50%,2019-03-15 21:46:58,2019-03-15 22:06:44,1.000000,1.640000,9.500000,1.70000,0.000000,14.160000
75%,2019-03-23 17:41:38,2019-03-23 17:51:56,2.000000,3.210000,15.000000,2.80000,0.000000,20.300000
max,2019-03-31 23:43:45,2019-04-01 00:13:58,6.000000,36.700000,150.000000,33.20000,24.020000,174.820000
std,NaN,NaN,1.203768,3.827867,11.551804,2.44856,1.415267,13.815570

In [44]:
# Count NULL values
taxis_df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [45]:
# Removing rows with NULL values
df = taxis_df.dropna()

In [46]:
# Converting target variable to numerical
le = LabelEncoder()
df['Payment'] = le.fit_transform(df['payment'])

C:\Users\Yug\AppData\Local\Temp\ipykernel_3280\425331654.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Payment'] = le.fit_transform(df['payment'])

In [47]:
# Select features for classification
X = df[['fare','distance','pickup_borough','dropoff_borough']]
X = pd.get_dummies(X, drop_first=True) #Encode categorical features
y = df['payment'] #Target(Cash or Card)

In [48]:
# Train-Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [49]:
# Scaling the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [50]:
# Train classifier on raw data
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_scaled, y_train)
y_pred = clf.predict(X_test_scaled)
print("Accuracy on raw data: ",metrics.accuracy_score(y_test, y_pred))

Accuracy on raw data:  0.6516942474389283

In [51]:
# Apply PCA (2 components)
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.fit_transform(X_test_scaled)

In [52]:
# Train classifier with PCA-transformed data
clf_pca = RandomForestClassifier(n_estimators=100, random_state=42)
clf_pca.fit(X_train_pca, y_train)
y_pred_pca2 = clf_pca.predict(X_test_pca)
print("Accuracy with PCA(2 components): ",metrics.accuracy_score(y_test, y_pred_pca2))

Accuracy with PCA(2 components):  0.6438140267927502

In [53]:
# Apply PCA (3 components)
pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.fit_transform(X_test_scaled)

In [54]:
# Train classifier with PCA-transformed data
clf_pca = RandomForestClassifier(n_estimators=100, random_state=42)
clf_pca.fit(X_train_pca, y_train)
y_pred_pca3 = clf_pca.predict(X_test_pca)
print("Accuracy with PCA(3 components): ",metrics.accuracy_score(y_test, y_pred_pca3))

Accuracy with PCA(3 components):  0.6895193065405831

In [55]:
# Summary
print("Accuracy of all: \n")
print("Accuracy on raw data: ",metrics.accuracy_score(y_test, y_pred))
print("Accuracy with PCA(2 components): ",metrics.accuracy_score(y_test, y_pred_pca2))
print("Accuracy with PCA(3 components): ",metrics.accuracy_score(y_test, y_pred_pca3))

Accuracy of all:

Accuracy on raw data:  0.6516942474389283
Accuracy with PCA(2 components):  0.6438140267927502
Accuracy with PCA(3 components):  0.6895193065405831